eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

name:
  value: emnabhs

spring:
  application:
    name: order-service  
  sleuth:
    sampler:
      probability: 1
  h2:
    console:
      enabled: true

logstash:
  host: localhost
  port: 5000
  queue-size: 512

management:
  endpoints:
    web:
      exposure:
        include: "*"
